### ISSUE TITLE
Can any user be added to a project?

### ISSUE THREAD

**Issue by thabils** [SELab-2/OSOC-4#382]
If a student does not have a skill required for a project, can this student be added to that project.

**Comment by StefVdHaute** [comment]
Yes, students don't always need to be a perfect match. Not being able to add a student missing a specific skill seems like an unnecessary roadblock.

**Comment by SimonVandeVyver** [comment]
I also think that should be possible. They want to be able to draft any student to any project, so I think this should be possible too.
