### ISSUE TITLE
Invitelink check on int

### ISSUE THREAD

**Issue by Jarne-Andries** [SELab-2/OSOC-4#397]
When the user clicks on the invite-link in the e-mail he/she received, the application crashes.
When the invite-key is generated, ascii is used (line 23) 
<img width="927" alt="image" src="https://user-images.githubusercontent.com/99811344/166811432-294acc82-0fc4-4bba-9d21-a2c64488cad6.png">

But when the invite-key is checked, an error occurs because it isn't an int (line 26)
<img width="927" alt="image" src="https://user-images.githubusercontent.com/99811344/166811582-391bf9ae-4460-4fc3-978d-3329e1bc7770.png">

**Comment by StefVdHaute** [comment]
In your second screenshot line 26. `db.redis.get(invitekey)` returns the user id associated with the invitekey. If this user id is not an int you have an invalid invitekey. Can you show the code you use to put the key in redis and how you get the key?

Also a tip: you can link to a line in the code.

**Comment by Jarne-Andries** [comment]
I am on the development branch and didn't change a thing...

**Comment by StefVdHaute** [comment]
In milestone 2 the invite process was working so if possible can you check to see what has changed since then?

**Comment by QuintenVervynck** [comment]
I just tested this on the dev branch and had 0 issues, try to `git pull` again, and test it again. If the issue stays we'll call so I can see what you're doing exactly.
