### ISSUE TITLE
Delete assigned student from project

### ISSUE THREAD

**Issue by Jarne-Andries** [SELab-2/OSOC-4#409]
The button (`x`) to delete a student from a project doesn't work
<img width="328" alt="image" src="https://user-images.githubusercontent.com/99811344/166927586-264b1a33-e54c-41a3-95ce-1a313709c310.png">

**Comment by thabils** [comment]
#351 this is the current draft to fix this. Waiting for issue #407 to merge this with development

**Comment by StefVdHaute** [comment]
Fixed in #467
