### ISSUE TITLE
Delete question tag doens't work

### ISSUE THREAD

**Issue by Jarne-Andries** [SELab-2/OSOC-4#430]

**Comment by SimonVandeVyver** [comment]
This is actually a backend problem, @victormylle is already aware of this.

**Comment by victormylle** [comment]
Is this issue stil present? It seems to work for me @Jarne-Andries @SimonVandeVyver

**Comment by QuintenVervynck** [comment]
closing this as @victormylle and myself cant replicate this bug anymore
