### ISSUE TITLE
Make `send invite` button non-clickable

### ISSUE THREAD

**Issue by Jarne-Andries** [SELab-2/OSOC-4#434]
One thing to note is that you can still click the send invite button when it has already been pressed and we're still waiting on the response for backend.

As this issue is on all popups I'll add an issue for it instead of fixing it here.

_Originally posted by @QuintenVervynck in https://github.com/SELab-2/OSOC-4/issues/422#issuecomment-1120165191_

**Comment by QuintenVervynck** [comment]
I've already added that issue here https://github.com/SELab-2/OSOC-4/issues/417

**Comment by QuintenVervynck** [comment]
if this is closed also check that checkbox because it isn't linked since you made the issue manually

**Comment by Jarne-Andries** [comment]
I overlooked it and will do
