### ISSUE TITLE
Question-tags: checkbox isn't correct (so you can't uncheck a checkbox)

### ISSUE THREAD

**Issue by Jarne-Andries** [SELab-2/OSOC-4#458]
When a checkbox of a questiontag get's checked (to show in select students), the card/information of the student gets changed (but not always), but if you go back to the settings of the questiontag, everything is unchecked.
That way it is impossible to uncheck a checkbos (and questiontag)

**Comment by SimonVandeVyver** [comment]
It seems that every patch to the backend fails. Editing question tags also doesn't work.

**Comment by SimonVandeVyver** [comment]
Changing visibility (showInList) of mandatory tags does not work, the patches fail.
Is it possible that this is a problem in the backend?
@victormylle @Vital7788 @QuintenVervynck

**Comment by SimonVandeVyver** [comment]
The group agreed that the showInList of mandatory tags should not change. They represent data that is mostly already visible in the student list. So we will not implement the feature to change the showInList of mandatory tags.
